#!/bin/sh

prefix="/data/see"
exec_prefix="${prefix}"
libdir="${exec_prefix}/lib"
includedir="${prefix}/include"

case "$1" in
    --version) 
	echo "see-3.1.1424" ;;
    --libs)
	echo "-L$libdir -lsee   " ;;
    --cppflags)
	echo "-I$includedir" ;;
    --prefix)
	echo "$prefix" ;;
    --exec-prefix)
	echo "$exec_prefix" ;;
    *)
	exec >&2
	test -z "$1" || echo "unknown flag: $1"
	echo "usage: $0 --<request>" 
	echo "  where --<request> is one of:"
	echo "     --version      - prints <package>-<version>"
	echo "     --libs         - prints linker flags"
	echo "     --cppflags     - prints preprocessor flags to use"
	echo "     --prefix       - prints installation prefix"
	echo "     --exec-prefix  - prints execution installation prefix"
	exit 1
	;;
esac
